In [176]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [177]:
train_data = pd.read_csv("train.csv")
train_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [178]:
test_data = pd.read_csv("test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [179]:
women = train_data.loc[train_data.Sex == 'female']["Survived"]
rate_women = sum(women)/len(women)

print("% of women who survived:", rate_women)

% of women who survived: 0.7420382165605095

In [180]:
men = train_data.loc[train_data.Sex == 'male']["Survived"]
rate_men = sum(men)/len(men)

print("% of men who survived:", rate_men)

% of men who survived: 0.18890814558058924

In [181]:
y = train_data["Survived"]
features = ["Pclass", "Sex", "Parch", "SibSp"]
X = pd.get_dummies(train_data[features])

In [182]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

def get_score(max_depth, train_X, val_X, train_y, val_y):
    model = RandomForestClassifier(n_estimators=200, max_depth=max_depth, random_state=1)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    score = accuracy_score(preds_val, val_y)
    return(score)

# split data into training and validation data, for both features and target
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

# compare MAE with differing values of max_leaf_nodes
for max_depth in range(2,11):
    my_score= get_score(max_depth, train_X, val_X, train_y, val_y)
    print("Max depth: ",max_depth, "Score: ", my_score)

Max depth:  2 Score:  0.7937219730941704
Max depth:  3 Score:  0.7982062780269058
Max depth:  4 Score:  0.8026905829596412
Max depth:  5 Score:  0.8026905829596412
Max depth:  6 Score:  0.7892376681614349
Max depth:  7 Score:  0.7892376681614349
Max depth:  8 Score:  0.7892376681614349
Max depth:  9 Score:  0.7892376681614349
Max depth:  10 Score:  0.7892376681614349

In [183]:
from sklearn.metrics import mean_absolute_error
#from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

def get_score(max_depth, train_X, val_X, train_y, val_y):
    model = RandomForestClassifier(n_estimators=200, max_depth=max_depth, random_state=1)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    score = accuracy_score(preds_val, val_y)
    return(score)

# split data into training and validation data, for both features and target
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

# compare MAE with differing values of max_leaf_nodes
for max_depth in range(2,11):
    my_score= get_score(max_depth, train_X, val_X, train_y, val_y)
    print("Max depth: ",max_depth, "Score: ", my_score)

Max depth:  2 Score:  0.7937219730941704
Max depth:  3 Score:  0.7982062780269058
Max depth:  4 Score:  0.8026905829596412
Max depth:  5 Score:  0.8026905829596412
Max depth:  6 Score:  0.7892376681614349
Max depth:  7 Score:  0.7892376681614349
Max depth:  8 Score:  0.7892376681614349
Max depth:  9 Score:  0.7892376681614349
Max depth:  10 Score:  0.7892376681614349

In [184]:
#Try with RandomTreeRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds)
    return(mae)

# split data into training and validation data, for both features and target
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

# compare MAE with differing values of max_leaf_nodes
for max_leaf_nodes in [2,5,8,10,15]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max depth: ", max_leaf_nodes, "Mean Absolute Error: ", my_mae)

Max depth:  2 Mean Absolute Error:  0.3360364789390658
Max depth:  5 Mean Absolute Error:  0.2834844530689407
Max depth:  8 Mean Absolute Error:  0.2708128187227177
Max depth:  10 Mean Absolute Error:  0.2714645839456067
Max depth:  15 Mean Absolute Error:  0.27007294988935143

In [185]:
#best result with RandomForestClassifier
X_test=pd.get_dummies(test_data[features])
model = RandomForestClassifier(n_estimators=100, max_depth=6, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

In [187]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv',index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [188]:
output

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]